import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from './footer'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Created by Razroo",
  description: "Generated by Razroo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <h1>Razroo</h1>
      <Footer/>
      </body>
  
    </html>
  );
}
